runtime: java11
entrypoint: 'java -cp * com.google.appengine.demo.jettymain.Main warfile.war'
env_variables:
  DB_INSTANCE: openjdk11:us-central1:sqlludojava11
  DB_DATABASE: ludojava11database
  DB_USER: root
  DB_PASSWORD: password
