runtime: java11
# The entry point is necessary to tell Vert.x where to store cached resources extracted from fat jars
entrypoint: 'java -Dvertx.cacheDirBase=/tmp -jar vertx-hello-j11-1.0-jar-with-dependencies.jar '
